[package]
name = "Expriment"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
lettre = "0.10.0-rc.3"
lettre_email = " 0.9.4"
tracing = "0.1.28"
tracing-subscriber = "0.2.23"